version: '3.3'
services:
    payments-api:
        container_name: payments-api
        image: payments-api:latest
        ports:
            - "3000:3000"
        # volumes:
            # - /usr/src/app/node_modules/    
        links:
            - mongodb
        depends_on:
            - mongodb
        # environment:
            # - DB_URL="mongodb://mongo"
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27000:27017"